services:
  - type: web
    name: kpg-webhook-otimizar
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && echo 'Build v2.2 - Fix GCS permissions'"
    startCommand: "gunicorn webhook_otimizar_imagem:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 5000
    secretFiles:
      - name: credentials.json
        path: /etc/secrets/credentials.json
